### ISSUE TITLE
Can't use imported code from custom files in scenes

### ISSUE THREAD

**Issue by visuallization** [geocine/phaser3-rollup-typescript#1]
Hey there!

First of all, thank you very much for this typescript phaser starter kit! It works much faster than the one from photonstorm and is a bliss to work with. :)

I experienced an issue and was wondering if you might know what's the problem.
If I want to use an imported variable in one of my scene files like:

```
import Phaser from 'phaser';

import { threshold } from '../data';

class Start extends Phaser.Scene {
  constructor() {
    super('Start');
  }

  public create() {
    console.log(threshold);
  }
}

export default Start;
```

When I run the code, I'll get the following error: 
![image](https://user-images.githubusercontent.com/6199277/85149883-1eadf200-b252-11ea-9d5b-cd84524938d1.png)

Can you help me out here?

Cheers,
Florentin

**Comment by geocine** [comment]
Hi just saw this today, may you try doing this
```js
import 'phaser';
```
Instead of 
```js
Import Phaser from 'phaser'
```
Here is an example code which imports stuff to the Game Scene
https://github.com/geocine/phaser3-road-cross

**Comment by visuallization** [comment]
@geocine sorry just saw I didn't answer back then. Thanks so much for your support! :)

**Comment by ubershmekel** [comment]
@geocine I tried that. Looking at your other projects, it seems that you don't have example with a `package.json` dependency. I'm trying right now to make a game with `howler` as a dependency and hitting a different error depending on how I import and fiddle with the rollup config. I'll update this thread if I figure it out.

**Comment by visuallization** [comment]
@ubershmekel Did you find a way to handle this? I am curious because eventually I will meet the same issue.

**Comment by geocine** [comment]
Hi @ubershmekel, just saw this. Do you have a repo I can check?

**Comment by ubershmekel** [comment]
Here you go https://github.com/ubershmekel/phaser3-rollup-typescript

**Comment by visuallization** [comment]
@ubershmekel uh nice, thanks for the repo link. :) Zero build time sounds awesome, but typescript support is also nice, especially if you are still learning phaser like I do.

**Comment by geocine** [comment]
Hi @ubershmekel and @visuallization I haven't been doing Phaser for a long time, so I was not able to make time for this. If you have solutions, I am open to suggestions.

**Comment by rafasnarf** [comment]
I'm having the same issue! The solution I have founded is using another template, but, that don't have hot reload :'(

**Comment by geocine** [comment]
@rafasnarf  @visuallization  @ubershmekel  I have fixed this issue and now it is faster than ever. I need you to test and confirm that the issue no longer exist

**Comment by visuallization** [comment]
@geocine uh nice, will check it out! :)

**Comment by visuallization** [comment]
@geocine So I added your updated version to my game and it works like a charm. Imports work they way I would expect them to and it is really fast. :)

Btw you could remove `process.env.NODE_ENV` from `vite.config.js` as vite provides the properties `import.meta.env.PROD` and `import.meta.env.DEV` https://vitejs.dev/guide/env-and-mode.html

Cheers and thanks for your work!
Florentin

**Comment by geocine** [comment]
Oh nice @visuallization I will do that
